# Site settings
title       : M. Appelman
description : I'm Dutch.
url         : https://huphtur.nl

# Build settings
excerpt_separator : <!--more-->
markdown          : kramdown
highlighter       : rouge
kramdown          :
  input           : GFM
permalink         : /:title/

sass:
style       : expanded
deploy_style: compressed
