# Site settings
title       : M. Appelman
description : I'm Dutch.
url         : https://huphtur.nl

# Build settings
markdown    : kramdown
highlighter : null
kramdown    :
  input     : GFM
permalink   : /:title/

sass:
style       : expanded
deploy_style: compressed
